import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

const MainGrey = Colors.grey;
const WeekGrey = Color(0xffeeeeee);
const MainWhite = Colors.white;
const MainRed = Color(0xFFBC2726);
const WeakRed = Color(0xFFFF5A5F);
const MainBlue = Color(0xFF009DCA);
const MainBlack = Colors.black;
const MainPink = Colors.pink;
const MainWhite1 = Color(0xfff9fafb);
const MainTrans = Colors.transparent;
const MainYellow = Colors.yellow;
const PureGreen = Colors.green;
const PureGrey = Colors.grey;
const BlueAccent = Colors.blueAccent;
const PureAmber = Colors.amber;
const MainGreen = Color(0xFF087E8B);
const DarkRed = Color(0xffcb2a42);
const DarkGrey = Color(0xff2b292a);
const Black = Color(0xff131313);
const DarkYellow = Color(0xFFEF6C00);
const SecondGrey = Color(0xFFADA169);
const WeakGrey = Color(0xFFEEEEEE);
const BlackTrans = Color(0xBB010101);
